# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='email',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='name',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
