# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('da', '0002_auto_20190404_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(default=b'', max_length=100)),
                ('h_city', models.CharField(default=b'', max_length=100)),
                ('h_address', models.TextField(default=b'', max_length=200)),
                ('h_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default=b'', max_length=100)),
                ('p_city', models.CharField(default=b'', max_length=100)),
                ('p_address', models.TextField(default=b'', max_length=200)),
                ('p_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name=b'dob'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='fname',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='lname',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
