# Generated by Django 2.2 on 2019-04-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0003_auto_20190405_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(default='', max_length=100)),
                ('no_of_deaths', models.IntegerField(default=0)),
                ('no_of_affected', models.IntegerField(default=0)),
                ('location', models.CharField(default='', max_length=100)),
                ('date', models.DateField(verbose_name='date')),
            ],
        ),
        migrations.AlterField(
            model_name='hospitalprofileinfo',
            name='h_address',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hospitalprofileinfo',
            name='h_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospitalprofileinfo',
            name='h_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacyprofileinfo',
            name='p_address',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pharmacyprofileinfo',
            name='p_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacyprofileinfo',
            name='p_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='dob'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='fname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='lname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
