# Generated by Django 2.2 on 2019-04-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0006_citymap_countrymap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrymap',
            old_name='city',
            new_name='country',
        ),
    ]
