# Generated by Django 2.2 on 2019-04-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0007_auto_20190415_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='citymap',
        ),
        migrations.DeleteModel(
            name='countrymap',
        ),
    ]
