# Generated by Django 2.2 on 2019-04-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0008_auto_20190416_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='outbreakform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('disease', models.CharField(choices=[('Ebola', 'Ebola'), ('Cholera', 'Cholera'), ('Dengue', 'Dengue'), ('Malaria', 'Malaria')], max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='hospitalprofileinfo',
            old_name='h_address',
            new_name='hospital_address',
        ),
        migrations.RenameField(
            model_name='hospitalprofileinfo',
            old_name='h_city',
            new_name='hospital_city',
        ),
        migrations.RenameField(
            model_name='hospitalprofileinfo',
            old_name='h_name',
            new_name='hospital_name',
        ),
        migrations.RenameField(
            model_name='hospitalprofileinfo',
            old_name='h_user',
            new_name='hospital_user',
        ),
        migrations.RenameField(
            model_name='pharmacyprofileinfo',
            old_name='p_address',
            new_name='pharmacy_address',
        ),
        migrations.RenameField(
            model_name='pharmacyprofileinfo',
            old_name='p_city',
            new_name='pharmacy_city',
        ),
        migrations.RenameField(
            model_name='pharmacyprofileinfo',
            old_name='p_name',
            new_name='pharmacy_name',
        ),
        migrations.RenameField(
            model_name='pharmacyprofileinfo',
            old_name='p_user',
            new_name='pharmacy_user',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='lname',
            new_name='last_name',
        ),
    ]
