# Generated by Django 2.2 on 2019-04-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0009_auto_20190417_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbreakform',
            name='disease',
            field=models.CharField(choices=[('Ebola', 'Ebola'), ('Cholera', 'Cholera'), ('Dengue', 'Dengue'), ('Malaria', 'Malaria')], max_length=30),
        ),
    ]
