# Generated by Django 2.2 on 2019-04-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0010_auto_20190417_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outbreak',
            old_name='date',
            new_name='o_date',
        ),
    ]
