# Generated by Django 2.2 on 2019-04-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0011_auto_20190417_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofileinfo',
            name='hospital_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pharmacyprofileinfo',
            name='pharmacy_address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
